name: ifsu.org
favicon: null
layout_spectrum: 0.40805
typography_spectrum: 0.70344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c0687'
    - '#fdc83b'
    - '#2094ff'
    - '#bc11c3'
  brandStrength: 0.625
  lightness: 0.08798167109489441
  saturation: 0.5820561773143709
  rhythmicContrast: 0.7603828764986247
purpose: []
